### ISSUE TITLE
setup github actions?

### ISSUE THREAD

**Issue by k-doering-NOAA** [Schiano-NOAA/ASAR#1]
@Schiano-NOAA would you like github actions to:

- make sure the r package builds appropriately on different OSes on every commit?
- Automatically update documentation and code style?
- check spelling?

If any of these sound useful, perhaps we can schedule a meeting to walk through setting them up with [ghactions4r](https://nmfs-fish-tools.github.io/ghactions4r/index.html)? I think we could set these up in an hour meeting.

**Comment by Schiano-NOAA** [comment]
These all sound like great things to set up! Please send me a meeting invite for a time that works for you.

**Comment by k-doering-NOAA** [comment]
@Schiano-NOAA it looks like it is renv that is causing the call-r-cmd-check action to not run all the way through. I tried taking out everything related to renv on [this branch](https://github.com/k-doering-NOAA/ASAR/tree/kd_changes) and the workflow ran through.

I think what is happening is it sets up the dependencies according to renv, but then doesn't use renv when running `check()` (because everything related to renv is in r build ignore), so there is a mismatch. Updating the lock file and ensuring it matches the DESCRIPTION might remove this mismatch, though?

I don't know much about renv, but I wonder if it is useful for a package that I think we will want to work with the most recent versions of packages? Philosophically, I'm not sure.  There are a few helpful vignettes available: one for [using renv with CI](https://rstudio.github.io/renv/articles/ci.html) and one for [developing packages](https://rstudio.github.io/renv/articles/packages.html).

I think there are ways to run gha and keep renv, though, if it feels helpful to you!

In the meantime, running `devtools::check()` in your local clone of ASAR should probably show some errors with package checking! I was able to run it in a codespace successfully.

**Comment by Schiano-NOAA** [comment]
Interesting. I will check this out and see if I can get the error to go away. Thanks for looking more into this.

**Comment by Schiano-NOAA** [comment]
Issue: dependencies were updated in DESCRIPTION file to reflect those in the renv lock file. The issue persisted. 

Solution: renv was disabled and associated files were deleted. Since the package was formally created, the renv environment isn't necessary since dependencies are called and loaded from the DESCRIPTION/NAMESPACE. Other errors found here was also fixed in subsequent edits.

**Comment by k-doering-NOAA** [comment]
Sounds good - We can definitely troubleshoot using renv in the future if needed!
