### ISSUE TITLE
[Bug]: create_template does not produce skeleton script

### ISSUE THREAD

**Issue by Schiano-NOAA** [Schiano-NOAA/ASAR#100]
### Describe the bug

When running create_template with some arguments I get the following error message:

`Error in grep(list.files(system.file("templates", "skeleton", package = "asar")),  : 
  invalid 'pattern' argument
In addition: Warning messages:
1: In asar::create_template(format = "pdf", office = "NWFSC", region = "U.S. West Coast",  :
  There are files in this location.
2: In asar::create_template(format = "pdf", office = "NWFSC", region = "U.S. West Coast",  :
  Rda directory and/or arguments needed to create .rda files not defined.
3: In asar::create_template(format = "pdf", office = "NWFSC", region = "U.S. West Coast",  :
  Rda directory and/or arguments needed to create .rda files not defined.`

### Describe how to reproduce the bug

`asar::create_template(
  format = "pdf",
  office = "NWFSC",
  region = "U.S. West Coast",
  species = "Sablefish",
  spp_latin = "Species latin",
  year = 2025,
  custom = TRUE,
  author = "Jon Snow",
  include_affiliation = TRUE,
  simple_affiliation = FALSE,
  convert_output = TRUE,
  resdir = "C:/Users/samantha.schiano/Documents/Stock Assessment Workflow/SS_output_examples/Sablefish/sablefish_20231219",
  model_results = "Report.sso",
  model = "SS3",
  make_rda = FALSE,
  #rda_dir = getwd(),
  #end_year = 2023
)`

### Which OS are you seeing the problem on?

Windows

### Which version of asar are you seeing the problem on?

main branch - current version

### Additional Context

This is a known but presented by another user and myself - we are actively working on it

**Comment by sbreitbart-NOAA** [comment]
Are rda_dir and end_year meant to be commented out? In the issue they present as Heading 1 size

**Comment by sbreitbart-NOAA** [comment]
I believe the issue is with including `custom = TRUE` when no custom sections (`custom_sections`) are indicated. Also, the `make_rda` argument shouldn't be included in `create_template()` because it is automatically determined by the function, as indicated in the `create_template` documentation. That's an understandable error... should that info be shown elsewhere? Also, I'll update the example that erroneously includes `make_rda` as an argument.

**Comment by Schiano-NOAA** [comment]
Yep this is right! I think it was a combination of not having things set up right and the issue with custom!
